#开启 Spring Boot 的 热部署 功能
spring.devtools.restart.enabled=true

# 指定 DevTools 除了监听默认目录（target/classes）之外，还要额外监控这个路径下的文件变动，一旦有改动就触发重启
spring.devtools.restart.additional-paths=src/mian/java


# 修改 Spring MVC 处理静态资源的 URL 访问前缀。
#通俗解释：你的图片、CSS、JS 等文件放在 src/main/resources/static/ 或 public/ 目录下。默认情况下，访问 localhost:8080/logo.png 就能直接拿到图片。
#加了这行后：你必须以 /images/ 开头才能访问到静态资源。
#spring.mvc.static-path-pattern=/images/**

#修改static路径
#spring.web.resources.static-locations=classpath:/css

spring.web.resources.static-locations=/upload/